# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12515ad6e64ec8b7ce70eed88eb9281308a3699a4971e50bae8eae40b2808b046c3f0139a452c3df676c390c076bc993782d30a192c891efbdabd59e34319f40

test:
  secret_key_base: d794a76dbf83a7841a918e254904b7a3e9eeae6af5bd910ada19391b6f2d8b09d69ad1a341e20250181343bb93aa519f8893c1ad31f8f7c127f1244617c77d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
